version: "3"

networks:
  db:

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5000:80'
    networks:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin