db:
  image: mysql/mysql-server
  ports:
    - "8080:8080"
  environment:
    - MYSQL_ROOT_PASSWORD=""
    - MYSQL_USER="me"
    - MYSQL_PASSWORD=""
    - MYSQL_DATABASE="mysql"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin

  restart: always
  ports:
    - "8082:8082"
  environment:
    PMA_HOST: mysql


